matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      env: ZSH_SRC=system
    - os: osx
      env: ZSH_SRC=homebrew
before_script:
- if [[ "$ZSH_SRC" == "homebrew" ]]; then brew install zsh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install zsh; fi
- mkdir .bin
- curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > .bin/revolver
- curl -L https://raw.githubusercontent.com/molovo/color/master/color.zsh > .bin/color
- curl -L https://github.com/molovo/zunit/releases/download/v0.6.4/zunit > .bin/zunit
- chmod u+x .bin/{color,revolver,zunit}
- export PATH="$PWD/.bin:$PATH"
script: zunit
